test_advancedindex_big_xpu (__main__.TestIndexingXPU) ... ok
test_advancedindex_xpu_float16 (__main__.TestIndexingXPU) ... ok
test_advancedindex_xpu_float64 (__main__.TestIndexingXPU) ... ok
test_basic_advanced_combined_xpu (__main__.TestIndexingXPU) ... ok
test_bool_indices_accumulate_xpu (__main__.TestIndexingXPU) ... ok
test_bool_indices_xpu (__main__.TestIndexingXPU) ... ok
test_byte_mask2d_xpu (__main__.TestIndexingXPU) ... ok
test_byte_mask_accumulate_xpu (__main__.TestIndexingXPU) ... ok
test_byte_mask_xpu (__main__.TestIndexingXPU) ... ok
test_byte_tensor_assignment_xpu (__main__.TestIndexingXPU) ... ok
test_cpu_indices_xpu (__main__.TestIndexingXPU) ... ok
test_ellipsis_tensor_xpu (__main__.TestIndexingXPU) ... ok
test_empty_index_xpu (__main__.TestIndexingXPU) ... ok
test_empty_ndim_index_bool_xpu (__main__.TestIndexingXPU) ... ok
test_empty_ndim_index_xpu (__main__.TestIndexingXPU) ... ERROR
test_empty_slice_xpu (__main__.TestIndexingXPU) ... ok
test_gather_take_along_dim_cross_device_xpu_float32 (__main__.TestIndexingXPU) ... ok
test_getitem_scalars_xpu (__main__.TestIndexingXPU) ... ok
test_index_getitem_copy_bools_slices_xpu (__main__.TestIndexingXPU) ... ok
test_index_put_accumulate_duplicate_indices_xpu (__main__.TestIndexingXPU) ... ok
test_index_put_accumulate_large_tensor_xpu (__main__.TestIndexingXPU) ... FAIL
test_index_put_src_datatype_xpu_bfloat16 (__main__.TestIndexingXPU) ... ok
test_index_put_src_datatype_xpu_bool (__main__.TestIndexingXPU) ... ok
test_index_put_src_datatype_xpu_complex128 (__main__.TestIndexingXPU) ... skipped 'dtype not support on XPU'
test_index_put_src_datatype_xpu_complex64 (__main__.TestIndexingXPU) ... skipped 'dtype not support on XPU'
test_index_put_src_datatype_xpu_float16 (__main__.TestIndexingXPU) ... ok
test_index_put_src_datatype_xpu_int64 (__main__.TestIndexingXPU) ... ok
test_index_scalar_with_bool_mask_xpu (__main__.TestIndexingXPU) ... ok
test_index_setitem_bools_slices_xpu (__main__.TestIndexingXPU) ... ok
test_index_src_datatype_xpu_bfloat16 (__main__.TestIndexingXPU) ... ok
test_index_src_datatype_xpu_bool (__main__.TestIndexingXPU) ... ok
test_index_src_datatype_xpu_float16 (__main__.TestIndexingXPU) ... ok
test_index_src_datatype_xpu_int64 (__main__.TestIndexingXPU) ... ok
test_index_xpu (__main__.TestIndexingXPU) ... ok
test_int_assignment_xpu (__main__.TestIndexingXPU) ... ok
test_int_indices2d_xpu (__main__.TestIndexingXPU) ... ok
test_int_indices_broadcast_xpu (__main__.TestIndexingXPU) ... ok
test_int_indices_xpu (__main__.TestIndexingXPU) ... ok
test_invalid_device_xpu (__main__.TestIndexingXPU) ... ok
test_invalid_index_xpu (__main__.TestIndexingXPU) ... ok
test_jit_indexing_xpu (__main__.TestIndexingXPU) ... ok
test_multiple_bool_indices_xpu (__main__.TestIndexingXPU) ... ok
test_multiple_byte_mask_xpu (__main__.TestIndexingXPU) ... ok
test_multiple_int_xpu (__main__.TestIndexingXPU) ... ok
test_none_xpu (__main__.TestIndexingXPU) ... ok
test_out_of_bound_index_xpu (__main__.TestIndexingXPU) ... ok
test_setitem_expansion_error_xpu (__main__.TestIndexingXPU) ... ok
test_setitem_scalars_xpu (__main__.TestIndexingXPU) ... ok
test_single_int_xpu (__main__.TestIndexingXPU) ... ok
test_step_assignment_xpu (__main__.TestIndexingXPU) ... ok
test_step_xpu (__main__.TestIndexingXPU) ... ok
test_take_along_dim_invalid_xpu_float32 (__main__.TestIndexingXPU) ... ok
test_take_along_dim_invalid_xpu_int64 (__main__.TestIndexingXPU) ... ok
test_take_along_dim_xpu_float32 (__main__.TestIndexingXPU) ... ERROR
test_take_along_dim_xpu_int64 (__main__.TestIndexingXPU) ... ERROR
test_variable_slicing_xpu (__main__.TestIndexingXPU) ... ok
test_zero_dim_index_xpu (__main__.TestIndexingXPU) ... ok

======================================================================
ERROR: test_empty_ndim_index_xpu (__main__.TestIndexingXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 402, in instantiated_test
    raise rte
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 889, in test_empty_ndim_index
    x[:, [0, 1]]
RuntimeError: index is out of bounds for dimension with size 0

======================================================================
ERROR: test_take_along_dim_xpu_float32 (__main__.TestIndexingXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 402, in instantiated_test
    raise rte
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1137, in test_take_along_dim
    _test_against_numpy(t, indices, 1)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1116, in _test_against_numpy
    actual = torch.take_along_dim(t, indices, dim=dim)
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.

======================================================================
ERROR: test_take_along_dim_xpu_int64 (__main__.TestIndexingXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 402, in instantiated_test
    raise rte
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1137, in test_take_along_dim
    _test_against_numpy(t, indices, 1)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1116, in _test_against_numpy
    actual = torch.take_along_dim(t, indices, dim=dim)
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.

======================================================================
FAIL: test_index_put_accumulate_large_tensor_xpu (__main__.TestIndexingXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 758, in test_index_put_accumulate_large_tensor
    self.assertEqual(a[:, 2], torch.ones(2, dtype=torch.int8))
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1877, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!Found 1 different element(s) (out of 2), with the greatest difference of 1 (0 vs. 1) occuring at index 1.

----------------------------------------------------------------------
Ran 57 tests in 48.922s

FAILED (failures=1, errors=3, skipped=2)
Raised CalledProcessError: return code 1.